version: '3'

services:
  transactions_mc:
    container_name: ng-cash-transaction-miroservice
    image: node:18-alpine3.15
    restart: 'always'
    tty: true
    volumes:
      - ./:/src/app
    environment:
      - PORT=3000

networks:
  default:
    external:
      name: rabbitmq-conn
